font:
  normal:
    family: HackGen Console NF
  bold:
    family: HackGen Console NF
  italic:
    family: HackGen Console NF
  bold_italic:
    family: HackGen Console NF
  size: 12.0

# window.opacity: 0.9
window:
  opacity: 0.9
  dimensions:
    columns: 200
    lines: 60
  padding:
    x: 8
    y: 4