#!/bin/sh

title(){
    echo "#=======================#"
    echo "# $1"
    echo "#=======================#"
}

# 現在のgit userを取得
current_user=$(git config user.name)
# 現在のgit emailを取得
current_email=$(git config user.email)

title "current user"
echo "user : $current_user"
echo "email: $current_email"

title "key check"

# 公開鍵の存在確認
if [ ! -e ~/.ssh/id_ed25519.pub ]; then
    echo "Don't exist public key."
    exit 1
else
    # ssh
    ssh -T git@github.com
fi