tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "bat"
brew "exa"
brew "git"
brew "go"
brew "neovim"
cask "alacritty"
cask "docker"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "google-chrome"
cask "visual-studio-code"
cask "zoom"
mas "LINE", id: 539883307
mas "Xcode", id: 497799835
