## arch linux docker compose
services:
  arch:
    # image: archlinux
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arch
    restart: always
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ./:/home/isksss/dotfiles
