[tools]
"aqua:rhysd/dotfiles" = "latest"
"aqua:jdx/usage" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:eza-community/eza" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:satococoa/wtp" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:starship/starship" = "1.24.2"
"npm:@antfu/ni" = "latest"
"github:neovim/neovim" = "nightly"

"aqua:jesseduffield/lazygit" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:zellij-org/zellij" = "latest"

go = "latest"
deno = "latest"
java = "temurin-8"
node = "24"
