[tools]
# shell / cli
"aqua:eza-community/eza" = "latest"
atuin = "latest"
bat = "latest"
delta = "latest"
fzf = "latest"
ghq = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
"usage" = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"

# shell enhancement
"cargo:sheldon" = "latest"
shfmt = "latest"

# vcs / forge
glab = { version = "latest", exe = "glab" }

# runtimes
deno = "latest"
go = "latest"
node = "24"
python = "latest"
uv = "latest"

# go tools
"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"
"go:github.com/rhysd/dotfiles" = "latest"

# npm tools
"npm:@antfu/ni" = "latest"
"npm:@github/copilot" = "latest"
"npm:@openai/codex" = "latest"
"npm:@playwright/cli" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:pg-formatter" = "latest"
"npm:playwright" = "latest"
"npm:sql-formatter" = "latest"

# python tools
"pipx:sqlfluff" = "latest"

# alt shell
"aqua:nushell/nushell" = "latest"

# OS管理
# OSに1password導入済み
# op = "latest"

[shell_alias]

[env]
EDITOR = "nvim"
LANG = "ja_JP.UTF-8"
LC_ALL = "ja_JP.UTF-8"
PAGER = "bat"

MISE_TRUSTED_CONFIG_PATHS = "/"

STARSHIP_CONFIG = "{{env.XDG_CONFIG_HOME}}/starship.toml"

XDG_CACHE_HOME = "{{env.HOME}}/.cache"
XDG_CONFIG_HOME = "{{env.HOME}}/.config"
XDG_DATA_HOME = "{{env.HOME}}/.local/share"
XDG_STATE_HOME = "{{env.HOME}}/.local/state"
