# test container
FROM archlinux/archlinux:base-devel

# ARG UID
# ARG GID
# ARG USERNAME
# ARG PASSWORD

# RUN groupadd -g $GID $USERNAME && \
#     groupadd sudo && \
#     useradd -m -s /bin/bash -u $UID -g $GID -G sudo $USERNAME && \
#     echo $USERNAME:$PASSWORD | chpasswd && \
#     echo "$USERNAME   ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# USER $USERNAME
# WORKDIR /home/$USERNAME/