#!/bin/zsh

## nvim のlsp設定

### python
pyenv versions || grep base-env >> /dev/null
if [ $? -gt 0 ]; then
  pyenv virtualenv 3.11 base-env >> /dev/null
fi

pyenv global base-env >> /dev/null
pip install --upgrade pip >> /dev/null

pip install -r ~/dotfiles/.config/nvim/requirements.txt >> /dev/null


if [ ! -d ~/Library/Fonts ]; then
  git clone https://github.com/powerline/fonts.git --depth=1
  cd ./Fonts
  ./install.sh
  cd ..
  rm -rf ./Fonts
fi

