
format = '''
[┌───────────────────>](bold green)
[│](bold green)$sudo$directory$git_branch$git_status$python$rust$golang$deno$package$os
[└─>](bold green) '''

scan_timeout = 10

add_newline = false

palette = 'foo'

[palettes.foo]
blue = '21'
mustard = '#af8700'
