[tools]
# tool
"usage" = "latest"
"fzf" = "latest"
ghq = "latest"
eza = "latest"
bat = "latest"
ripgrep = 'latest'
delta = "latest"
starship = 'latest'
neovim = "latest"
lazygit = "latest"
chezmoi = "latest"

"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"

# runtime
go = 'latest'
node = "24"
"npm:@github/copilot" = "latest"

[shell_alias]
# 基本
cl = "clear"
l = "ls"
ll = "ls -la"
la = "ls -A"

# 追加ツール
ls = "eza"
cat = "bat"
cz = "chezmoi"

[env]
XDG_CONFIG_HOME = "{{env.HOME}}/.config"
XDG_CACHE_HOME = "{{env.HOME}}/.cache"
XDG_DATA_HOME = "{{env.HOME}}/.local/share"
XDG_STATE_HOME = "{{env.HOME}}/.local/state"

# LANG = "ja_JP.UTF-8"
EDITOR = "nvim"
PAGER = "bat"

STARSHIP_CONFIG = "{{env.XDG_CONFIG_HOME}}/starship.toml"
