[settings]
experimental = true

[tools]
# lang
java = "openjdk-21"
go = "latest"
deno = "latest"
gradle = "8.10.2"
# tool
## cargo
"cargo:starship" = "latest"
"cargo:eza" = "latest"
"cargo:zoxide" = "latest"
"cargo:bat" = "latest"
"cargo:ripgrep" = "latest"
## go
"go:github.com/junegunn/fzf" = "latest"
"go:github.com/rhysd/dotfiles" = "latest"
## tools
neovim = "nightly"
